FROM debian:buster

SHELL ["/bin/bash", "--login", "-c"]

RUN su -

RUN apt upgrade && apt update && apt-get install vim -y

RUN apt-get install -y curl wget

RUN apt install nodejs  npm -y

RUN npm install -g @nestjs/cli

RUN cd ~

RUN curl -o- https://github.com/enesozmert/ft-transcendence.git | bash

RUN cd ft-transcendence.

RUN npm i 

RUN npm run start