FROM debian:buster

RUN apt upgrade && apt update && apt-get install curl git vim -y

#RUN apt install nodejs  npm -y
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
RUN export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
RUN [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
RUN nvm install 20
RUN nvm use 20

#RUN npm install -g @nestjs/cli

RUN git clone  https://github.com/enesozmert/ft-transcendence.git /ft-transcendence

WORKDIR /ft-transcendence
RUN npm install
cmd ["npm", " run start"]